[project]
name = 'Decentralized-Community-Solar-Project-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.installation-verification]
path = 'contracts/installation-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-tracking]
path = 'contracts/outcome-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.participant-management]
path = 'contracts/participant-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
